FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:13.9

VOLUME "/bot-files"

WORKDIR /bot-files
# bundle scripts for bot
COPY *.sh ./

RUN git clone https://github.com/BobertoBobert/QUB-Computing-Discord.git
RUN chmod -R 774
RUN /nodeinstall.sh 

CMD ["node", "index.js"]